// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {functions} from '../models';

export function ConnectToRedisDB(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function DeleteDBCredentials(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ReadDBCredentials():Promise<Array<functions.RedisLogin>>;

export function TestWailsNet():Promise<Array<number>>;
