// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToRedisDB(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConnectToRedisDB'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteDBCredentials(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DeleteDBCredentials'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadDBCredentials() {
  return window['go']['main']['App']['ReadDBCredentials']();
}

export function TestWailsNet() {
  return window['go']['main']['App']['TestWailsNet']();
}
